config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'subscriptions/create'
  get 'subscriptions/destroy'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  concern :votable do
    member do
      post :upvote
      post :downvote
      delete :cancel_vote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: %i[index show], shallow: true do
      patch :make_best, on: :member
    end

    resources :votes, only: %i[create destroy], shallow: true
    resources :subscriptions, only: %i[create destroy]
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  scope :all_for_day_before, -> { where('created_at > ?', 1.day.ago) }

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :badge, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :author, class_name: 'User'

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true

  def best_answer
    answers.where(best: true).first
  end

  after_create :calculate_reputation
  after_create :subscribe_author

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    self.subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      before_action :find_question, only: %i[show update destroy]

      authorize_resource

      def index
        @questions = Question.all
        render json: @questions
      end

      def show
        render json: @question
      end

      def create
        @question = Question.new(question_params)
        @question.author = current_resource_owner

        if @question.save
          render json: @question, serializer: QuestionSerializer
        else
          render json: @question.errors.messages.to_json, status: :unprocessable_entity
        end
      end

      def update
        if @question.update(question_params)
          render json: @question, serializer: QuestionSerializer
        else
          render json: @question.errors.messages.to_json, status: :unprocessable_entity
        end
      end

      def destroy
        @question.destroy
      end

      private

      def find_question
        @question = Question.find(params[:id])
      end

      def question_params
        params.require(:question).permit(:title, :body, files: [],
                                                        links_attributes: %i[name url id _destroy],
                                                        reward_attributes: %i[name image])
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  include Voted

  expose :questions, -> { Question.all }
  expose :question, scope: -> { Question.with_attached_files }
  expose :answer, -> { question.answers.new }

  before_action :set_question, only: :update

  authorize_resource

  before_action :set_gon_question_id
  after_action :publish_question, only: [:create]

  def new
    question.links.build
    question.build_badge
  end

  def index
    gon.current_user = current_user
  end

  def show
    answer.links.build
    gon.current_user = current_user
  end

  def create
    current_user.questions.push(question)

    if question.save
      redirect_to question, notice: 'Your question was successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    unless current_user.author_of?(question)
      redirect_to question_path(question), notice: 'You are not author of this question!'
      return
    end
    question.destroy
    redirect_to questions_path, notice: 'Question was successfully deleted.'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                                    links_attributes: %i[name url _destroy id],
                                                    badge_attributes: %i[title image _destroy id])
  end

  def set_gon_question_id
    gon.question_id = question.id
  end

  def publish_question
    return if question.errors.any?

    ActionCable.server.broadcast 'questions', question
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.slim
p
  = f.label :title
  = f.text_field :title
p
  = f.label :body
  = f.text_area :body

p
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true

p Links:
p = f.fields_for :links do |link_form|
  = render 'shared/links_form', f: link_form
.links
  = link_to_add_association 'Add link', f, :links, partial: 'shared/links_form'

- unless question.persisted?
  p Badge:
  p = f.fields_for :badge do |badge_form|
    = render 'badges/form', f: badge_form

- if question.persisted?
  p= f.submit 'Save'
- else
  p= f.submit 'Ask'

app/views/questions/_question.html.slim
h1= question.title
p= question.body

- if question.files.attached?
  .question-files
    - question.files.each do |file|
      p id="file-#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        '
        - if can? :destroy, file
          = link_to 'Delete file', file_path(file), method: :delete, remote: true

= render partial: 'links/links', locals: { resource: question }

= render partial: 'badges/badge_of_question', locals: { question: question }

p= 'Comments:'
div id="question-#{question.id}-comments"
  = render question.comments
.new-question-comment
  = render 'comments/form', commentable: question

- if can? :destroy, question

  = link_to 'Delete question', question_path(question), method: :delete
  '
  = link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }

  .question-errors
    = render 'shared/errors', resource: question

  = form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
    = render 'questions/form', f: f, question: question

.subscribe-links
  - if can? :create, Subscription
    = show_subscription_links(question)

div id="question-#{question.id}-votes"
  div id="question-#{question.id}-votes-errors"
  ' Rating:
  = show_rating_of(question)
  - if can? :upvote, question
    .links_for_voting
      = add_vote_links_to(question)

app/views/questions/index.html.slim
h1= 'All questions'

table id="questions-table"
  thead
    tr
      th Title
  tbody
    - questions.each do |question|
      tr
        td = link_to "#{question.title}", question_path(question)
        - if can? :destroy, question
          td= link_to 'Delete question', question_path(question), method: :delete

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  = render 'questions/form', f: f, question: question

app/views/questions/show.html.slim
div id="question-#{question.id}" class="question"
  = render question

br

.answers
  = render question.answers

h3= 'Create new answer'
.answer-errors
  = render 'shared/errors', resource: answer
= form_with model: [question, answer], local: false, class: 'new-answer', data: { type: :json } do |a|
  = render 'answers/form', a: a, answer: answer

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
$('.question').html('<%= j render @question %>');
<% end %>