config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'subscriptions/create'
  get 'subscriptions/destroy'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  concern :votable do
    member do
      post :upvote
      post :downvote
      delete :cancel_vote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: %i[index show], shallow: true do
      patch :make_best, on: :member
    end

    resources :votes, only: %i[create destroy], shallow: true
    resources :subscriptions, only: %i[create destroy]
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  mount ActionCable.server => '/cable'
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  belongs_to :question
  has_one :user_badge, dependent: :destroy
  has_one :user, through: :user_badge

  has_one_attached :image

  validates :title, :image, presence: true
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def index
    @badges = current_user.badges.all
  end
end

app/helpers/badges_helper.rb
# frozen_string_literal: true

module BadgesHelper
end

app/views/badges/_badge.html.slim
h3= badge.title
p
  'Badge for question:
  = link_to "#{badge.question.title}", question_path(badge.question)
  br
  = link_to 'Badge image', url_for(badge.image)

app/views/badges/_badge_of_question.html.slim
- if question.badge.present?
  b Badge:
  p= question.badge.title
  p= link_to 'Reward image', url_for(question.badge.image)

app/views/badges/_form.html.slim
.nested-fields
  .field
    = f.label :title, 'Badge title'
    = f.text_field :title
  .field
    = f.label :image
    = f.file_field :image
  = link_to_remove_association "Remove badge", f

app/views/badges/index.html.slim
h1 Your badges

- current_user.badges.each do |badge|
  = render badge