config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'subscriptions/create'
  get 'subscriptions/destroy'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  concern :votable do
    member do
      post :upvote
      post :downvote
      delete :cancel_vote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: %i[index show], shallow: true do
      patch :make_best, on: :member
    end

    resources :votes, only: %i[create destroy], shallow: true
    resources :subscriptions, only: %i[create destroy]
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  default_scope -> { order(best: :desc, created_at: :asc) }

  include Votable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: 'User'
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :notify_subscribed

  def make_best
    previous_best = question.best_answer

    Answer.transaction do
      if previous_best&.persisted?
        previous_best.update!(best: false)
        previous_best.author.badges.delete(question.badge) unless question.badge.nil?
      end

      update!(best: true)
      question.badge&.update!(user: author)
    end
  end

  private

  def notify_subscribed
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!

  include Voted

  expose :question, -> { Question.find(params[:question_id]) }

  before_action :set_answer, except: :create

  authorize_resource

  after_action :publish_answer, only: [:create]

  def create
    @answer = question.answers.new(answer_params.merge({ author: current_user }))

    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json do
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
  end

  def make_best
    @question = @answer.question

    @answer.make_best
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url _destroy id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast "question_#{@answer.question.id}/answers", answer: @answer
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = answer.question
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      before_action :find_answer, only: %i[show update destroy]

      authorize_resource

      def index
        @answers = Question.find(params[:question_id]).answers
        render json: @answers, each_serializer: AnswerSerializer
      end

      def show
        render json: @answer, serializer: AnswerSerializer
      end

      def create
        @answer = Question.find(params[:question_id]).answers.create(answer_params)
        @answer.author = current_resource_owner

        if @answer.save
          render json: @answer, serializer: AnswerSerializer
        else
          render json: @answer.errors.messages.to_json, status: :unprocessable_entity
        end
      end

      def update
        if @answer.update(answer_params)
          render json: @answer, serializer: AnswerSerializer
        else
          render json: @answer.errors.messages.to_json, status: :unprocessable_entity
        end
      end

      def destroy
        @answer.destroy
      end

      private

      def find_answer
        @answer = Answer.find(params[:id])
      end

      def answer_params
        params.require(:answer).permit(:title, :body, files: [],
                                                      links_attributes: %i[name url id _destroy])
      end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
div id="answer-#{answer.id}"
  = answer.body
  - if answer.files.attached?
    br
    - answer.files.each do |file|
      span id="file-#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        '
        - if can? :destroy, file
          = link_to 'Delete file', file_path(file), method: :delete, remote: true
          '
    br
  '
  = render partial: 'links/links', locals: { resource: answer }

  - if answer.best?
    b= 'Best'
    '

  - if answer.persisted? and (can? :make_best, answer) and not answer.best?
    = link_to 'Make best', make_best_answer_path(answer), method: :patch, remote: true
    '

  - if answer.persisted? && (can? :destroy, answer)
    = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
    '
    = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    '
    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = render 'answers/form', a: f, answer: answer

  p= 'Comments:'
  div id="answer-#{answer.id}-comments"
    = render answer.comments
  .new-answer-comment
    = render 'comments/form', commentable: answer

  div id="answer-#{answer.id}-votes"
    div id="answer-#{answer.id}-votes-errors"
    - if answer.persisted?
      ' Rating:
      = show_rating_of(answer)
      - if can? :upvote, answer
        .links_for_voting
          = add_vote_links_to(answer)

app/views/answers/_form.html.slim
p
  = a.label :body, 'Your answer'
  = a.text_area :body

p
  = a.label :files
  = a.file_field :files, multiple: true, direct_upload: true

p Links:
p= a.fields_for :links do |link_form|
  = render 'shared/links_form', f: link_form
.links
  = link_to_add_association 'Add link', a, :links, partial: 'shared/links_form'

- if answer.persisted?
  p= a.submit 'Save'
- else
  p= a.submit 'Create Answer'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer #answer_files').val('');
<% end %>

app/views/answers/destroy.js.erb
$("#answer-<%= @answer.id %>").remove();

app/views/answers/make_best.js.erb
$(".answers").html('<%= j render @question.answers %>');

app/views/answers/new.html.slim
= form_with model: [question, answer], local: false, class: 'new-answer' do |a|
  = render 'answers/form', a: a, answer: answer

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>