config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'subscriptions/create'
  get 'subscriptions/destroy'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  concern :votable do
    member do
      post :upvote
      post :downvote
      delete :cancel_vote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: %i[index show], shallow: true do
      patch :make_best, on: :member
    end

    resources :votes, only: %i[create destroy], shallow: true
    resources :subscriptions, only: %i[create destroy]
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  mount ActionCable.server => '/cable'
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true

  validates :url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])

  def is_gist?
    url.include? 'gist.github.com'
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link

  def destroy
    authorize! :destroy, @link

    @link.destroy
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end
end

app/helpers/links_helper.rb
# frozen_string_literal: true

module LinksHelper
  def get_gist_files(url)
    client = Octokit::Client.new(access_token: Rails.application.credentials[:github_access_token])
    id = url.split('/').last
    returned_gist = client.gist(id)
    returned_gist[:files]
  end
end

app/views/links/_link.html.slim
li id="link_#{link.id}"
  - if link.is_gist?
    - get_gist_files(link.url).each do |filename, gist_data|
      = link_to link.name, link.url
      ':
      = gist_data[:content]
  - else
    = link_to link.name, link.url
  '
  - if can? :destroy, link
    = link_to 'Delete link', link_path(link), method: :delete, remote: true

app/views/links/_links.html.slim
- if resource.persisted?
  .links id="links_for_#{resource.class.to_s.downcase}_#{resource.id}"
    - if resource.links.present?
      p Links:
      ul
        - resource.links.each do |link|
          = render link

app/views/links/destroy.js.erb
$('#link_<%= @link.id %>').remove();